import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Providers from "@/app/provider";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl" >
        <body
            className={`${geistSans.variable} ${geistMono.variable}
         flex flex-col h-screen bg-gray-200 antialiased`
            }>
        <Header/>
        <div className="flex h-screen">
            <Sidebar/>
            <Providers>
                <div className="container flex flex-col mx-auto py-10">
                    {children}
                </div>
            </Providers>
        </div>
        </body>
        </html>
    );
}
