import {Geist, Geist_Mono} from "next/font/google";
import Sidebar from "../components/sidebar";
import Header from "../components/header";
import {ThemeProvider} from "../components/theme-provider";
import QueryProviders from "@/lib/QueryProviders";
import "./globals.css";

import type {Metadata} from "next";
import {type ReactNode} from 'react';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <body
            className={`${geistSans.variable} ${geistMono.variable}
         flex flex-col h-screen bg-gray-200 antialiased`
            }>
        <ThemeProvider>
            <Header/>
            <div className="grid grid-cols-12 w-full h-screen">
                <div className="col-span-2">
                    <Sidebar/>
                </div>
                <div className="container flex flex-col col-span-10 mx-auto p-10">
                    <QueryProviders>
                        {children}
                    </QueryProviders>
                </div>
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
